(set-logic SLHV)

(declare-hvar emp IntHeap)
(declare-locvar nil IntLoc)
(declare-hvar h0 IntHeap)
(declare-hvar h1 IntHeap)
(declare-locvar head0 IntLoc)
(declare-locvar head1 IntLoc)
(declare-locvar curr0 IntLoc)
(declare-locvar curr1 IntLoc)
(declare-locvar temp0 IntLoc)
(declare-locvar temp1 IntLoc)


(declare-locvar loc0 IntLoc)
(declare-locvar loc1 IntLoc)
(declare-locvar pos1 IntLoc)
(declare-locvar pos2 IntLoc)
(declare-locvar pos3 IntLoc)
(declare-locvar pos4 IntLoc)

(declare-hvar h1_B2 IntHeap)
(declare-locvar x_B2 IntLoc)
(declare-locvar x_B4 IntLoc)

(assert (and 
    (distinct head0 loc0)
    (distinct head1 loc0)
    (distinct curr0 loc0)
    (distinct curr1 loc0)
    (distinct temp0 loc0)
    (distinct temp1 loc0)
    (distinct head0 loc1)
    (distinct head1 loc1)
    (distinct curr0 loc1)
    (distinct curr1 loc1)
    (distinct temp0 loc1)
    (distinct temp1 loc1)
    (distinct head0 pos1)
    (distinct head1 pos1)
    (distinct curr0 pos1)
    (distinct curr1 pos1)
    (distinct temp0 pos1)
    (distinct temp1 pos1)
    (distinct head0 pos2)
    (distinct head1 pos2)
    (distinct curr0 pos2)
    (distinct curr1 pos2)
    (distinct temp0 pos2)
    (distinct temp1 pos2)
    (distinct head0 pos3)
    (distinct head1 pos3)
    (distinct curr0 pos3)
    (distinct curr1 pos3)
    (distinct temp0 pos3)
    (distinct temp1 pos3)
    (distinct head0 pos4)
    (distinct head1 pos4)
    (distinct curr0 pos4)
    (distinct curr1 pos4)
    (distinct temp0 pos4)
    (distinct temp1 pos4)
    (distinct pos1 pos2)
    (distinct pos1 pos3)
    (distinct pos1 pos4)
    (distinct pos2 pos3)
    (distinct pos2 pos4)
    (distinct pos3 pos4)
))
(assert (= loc0 pos1))
(assert (or (distinct loc0 pos1) (and 
    (= h0 emp)
    (= h1 (pt head1 nil))
    (= curr1 head1)
    (= temp1 temp0)
    (= loc1 pos2)
)))
(assert (or (distinct loc0 pos2) (and 
    (= (h0 (uplus (pt curr0 x_B2) h1_B2)))
    (= h1 (uplus (pt temp1 nil) (pt curr0 temp1) h1))
    (= curr1 temp1)
    (= head1 head0)
    (= loc1 pos2)
)))
(assert (or (distinct loc0 pos2) (and 
    (= curr1 head0)
    (= head1 head0)
    (= temp1 temp0)
    (= h1 h0)
    (= loc1 pos3)
)))
(assert (or (distinct loc0 pos3) (and 
    (distinct curr0 nil)
    (= h0 (uplus (pt curr0 x_B4) h1))
    (= temp1 x_B4)
    (= temp1 curr1)
    (= head0 head1)
    (= loc1 pos3)
)))
(assert (or (distinct loc0 pos3) (and 
    (= curr0 nil)
    (= head1 head0)
    (= curr1 curr0)
    (= temp1 temp0)
    (= loc1 pos4)
)))

(check-sat)
